/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Operaciones;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Memoria;
import modelo.Particion;
import modelo.Proceso;

/**
 *
 * @author Tita
 */
public class NuevoPrograma extends javax.swing.JFrame {
    Operaciones oper = new Operaciones();
    DefaultTableModel procesos = new DefaultTableModel();
    ArrayList<Proceso> listaprocesos = new ArrayList<>();
    ArrayList<Particion> particiones;
    int tamMemFija = 0;
    int tamPart = 0;
    int mayorProceso = 0;
    /**
     * Creates new form NuevoPrograma
     */
    public NuevoPrograma() {
        initComponents();
        this.setLocationRelativeTo(null);
        setModeloProcesos();
        
    }
    
    private void setModeloProcesos(){
        String[] cabecera = {"Nro Proceso", "Tiempo de Arribo", "Tamaño", "CPU", "E/S 1", "CPU", "E/S 2", "CPU"};
        procesos.setColumnIdentifiers(cabecera);
        jTable1.setModel(procesos);
    }
    
    private void llenarListaProcesos(){
       Integer rafcpu = Integer.parseInt((String)rafagascpu.getSelectedItem());
       Integer tarribo = Integer.parseInt(tiempoarribo.getText());
       Integer tama = Integer.parseInt(tamanio.getText());
       Integer cpu1_ = Integer.parseInt(cpu1.getText());
       if ((String)rafagascpu.getSelectedItem()=="2") {
           Integer entsal1_ = Integer.parseInt(entsal1.getText());
           Integer cpu2_ = Integer.parseInt(cpu2.getText());
           Proceso proceso = new Proceso(rafcpu, tarribo, tama, cpu1_, entsal1_, cpu2_);
           listaprocesos.add(proceso);
       } else if ((String)rafagascpu.getSelectedItem()=="3") {
           Integer entsal1_ = Integer.parseInt(entsal1.getText());
           Integer cpu2_ = Integer.parseInt(cpu2.getText());
           Integer entsal2_ = Integer.parseInt(entsal2.getText());
           Integer cpu3_ = Integer.parseInt(cpu3.getText());
           Proceso proceso = new Proceso(rafcpu, tarribo, tama, cpu1_, entsal1_, cpu2_, entsal2_, cpu3_);
           listaprocesos.add(proceso);
       } else {
           Proceso proceso = new Proceso(rafcpu, tarribo, tama, cpu1_);
           listaprocesos.add(proceso);
       }
       
    }
    
    private void setDatosProcesos(){
        Object[] datos = new Object[procesos.getColumnCount()];
        int i = 1;
        procesos.setRowCount(0);
        for (Proceso proceso : listaprocesos){
            datos[0] = i;
            datos[1] = proceso.getTiempoarribo();
            datos[2] = proceso.getTamanio();
            datos[3] = proceso.getCpu1();
            datos[4] = proceso.getEntsal1();
            datos[5] = proceso.getCpu2();
            datos[6] = proceso.getEntsal2();
            datos[7] = proceso.getCpu3();
            i++;
            procesos.addRow(datos);
        }
        jTable1.setModel(procesos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tammemo = new javax.swing.JTextField();
        quantum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        algplanp = new javax.swing.JComboBox<>();
        tipopart = new javax.swing.JComboBox<>();
        combovariable = new javax.swing.JComboBox<>();
        combofija = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nropart = new javax.swing.JComboBox<>();
        fondomemo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fondomemo2 = new javax.swing.JLabel();
        rafagascpu = new javax.swing.JComboBox<>();
        tiempoarribo = new javax.swing.JTextField();
        tamanio = new javax.swing.JTextField();
        cpu1 = new javax.swing.JTextField();
        entsal1 = new javax.swing.JTextField();
        cpu2 = new javax.swing.JTextField();
        entsal2 = new javax.swing.JTextField();
        cpu3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        agregarp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fondomemo1 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Programa");
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionActionPerformed(evt);
            }
        });
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, -1));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Configuracion Inicial de Memoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Nuevo Programa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));
        getContentPane().add(tammemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 100, -1));

        quantum.setEnabled(false);
        getContentPane().add(quantum, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 70, -1));

        jLabel3.setText("Descripcion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel4.setText("Tipo de Particion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel5.setText("Asignacion de Memoria");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel6.setText("Tamaño de Memoria");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel7.setText("Numero de Particiones");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel8.setText("Planificacion de Procesos");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel9.setText("Quantum");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        algplanp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "Round Robin", "SJF", "SRTF" }));
        algplanp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                algplanpItemStateChanged(evt);
            }
        });
        algplanp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                algplanpMouseClicked(evt);
            }
        });
        getContentPane().add(algplanp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        tipopart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Variable", "Fija" }));
        tipopart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipopartItemStateChanged(evt);
            }
        });
        getContentPane().add(tipopart, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 90, -1));

        combovariable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First-Fit", "Worst-Fit" }));
        combovariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combovariableActionPerformed(evt);
            }
        });
        getContentPane().add(combovariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, -1));

        combofija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First-Fit", "Best-Fit" }));
        getContentPane().add(combofija, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, -1));

        jLabel10.setText("Algoritmo de");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 185, -1, -1));

        jLabel11.setText("Algoritmo de");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 185, -1, -1));

        nropart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", " " }));
        nropart.setEnabled(false);
        nropart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nropartItemStateChanged(evt);
            }
        });
        nropart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nropartActionPerformed(evt);
            }
        });
        getContentPane().add(nropart, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 70, -1));

        fondomemo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoblanco.png"))); // NOI18N
        getContentPane().add(fondomemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 100, 626, 160));

        jLabel12.setText("Rafagas CPU");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel13.setText("Tiempo Arribo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel14.setText("Tamaño");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jLabel15.setText("CPU");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jLabel16.setText("E/S 1");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        jLabel17.setText("CPU");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jLabel18.setText("E/S 2");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jLabel19.setText("CPU");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        fondomemo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondomorado.png"))); // NOI18N
        getContentPane().add(fondomemo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 60, 640, 205));

        rafagascpu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        rafagascpu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rafagascpuItemStateChanged(evt);
            }
        });
        getContentPane().add(rafagascpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 50, -1));
        getContentPane().add(tiempoarribo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 50, -1));
        getContentPane().add(tamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 50, -1));
        getContentPane().add(cpu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 50, -1));

        entsal1.setEnabled(false);
        getContentPane().add(entsal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 50, -1));

        cpu2.setEnabled(false);
        getContentPane().add(cpu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 50, -1));

        entsal2.setEnabled(false);
        getContentPane().add(entsal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 50, -1));

        cpu3.setEnabled(false);
        getContentPane().add(cpu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 50, -1));

        jLabel20.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel20.setText("Carga de Procesos");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 325, -1, -1));

        agregarp.setText("Agregar Proceso");
        agregarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarpActionPerformed(evt);
            }
        });
        getContentPane().add(agregarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 415, -1, -1));

        jButton1.setText("Guardar y Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro Proceso", "Tiempo Arribo", "Tamaño", "CPU ", "E/S 1", "CPU", "E/S 2", "CPU"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 630, 160));

        fondomemo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondomorado.png"))); // NOI18N
        getContentPane().add(fondomemo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 320, 640, 295));

        guardar.setText("Guardar Programa");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, -1, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoblanco.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionActionPerformed

    private void algplanpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algplanpMouseClicked

    }//GEN-LAST:event_algplanpMouseClicked

    private void algplanpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_algplanpItemStateChanged
       if ((String)algplanp.getSelectedItem()=="Round Robin"){
            quantum.setEnabled(true);
    } else{
        quantum.setEnabled(false);
        }
    }//GEN-LAST:event_algplanpItemStateChanged

    private void rafagascpuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rafagascpuItemStateChanged
        if ((String)rafagascpu.getSelectedItem()=="2"){
            entsal1.setEnabled(true);
            cpu2.setEnabled(true);
        } else if ((String)rafagascpu.getSelectedItem()=="3"){
            entsal2.setEnabled(true);
            cpu3.setEnabled(true);
        } else if ((String)rafagascpu.getSelectedItem()=="1"){
          entsal1.setEnabled(false);
          entsal2.setEnabled(false);
          cpu2.setEnabled(false);
          cpu3.setEnabled(false);
        }
    }//GEN-LAST:event_rafagascpuItemStateChanged

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        Principal principal = new Principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void agregarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarpActionPerformed
        llenarListaProcesos();
        tiempoarribo.setText(null);
        tamanio.setText(null);
        cpu1.setText(null);
        entsal1.setText(null);
        cpu2.setText(null);
        entsal2.setText(null);
        cpu3.setText(null);
        setDatosProcesos();
    }//GEN-LAST:event_agregarpActionPerformed

    private void tipopartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipopartItemStateChanged
        if ((String)tipopart.getSelectedItem()=="Variable"){
            combovariable.setVisible(true);
            combofija.setVisible(false);
            tammemo.setEnabled(true);
            nropart.setEnabled(false);
        } else if ((String)tipopart.getSelectedItem()=="Fija"){
            combovariable.setVisible(false);
            combofija.setVisible(true);
            tammemo.setEnabled(false);
            nropart.setEnabled(true);
        }
    }//GEN-LAST:event_tipopartItemStateChanged

    private void combovariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combovariableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combovariableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        if ((String)tipopart.getSelectedItem()=="Variable"){
        Memoria memoria = new Memoria(descripcion.getText(), (String)tipopart.getSelectedItem(),
                (String)combovariable.getSelectedItem(), Integer.parseInt(tammemo.getText()), 
                (String)algplanp.getSelectedItem());
        oper.altaMemoria(memoria, listaprocesos);
        } else {
         
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void nropartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nropartItemStateChanged
        
    }//GEN-LAST:event_nropartItemStateChanged

    private void nropartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nropartActionPerformed
        int cantpar = Integer.parseInt((String)nropart.getSelectedItem());
        System.out.println(cantpar);
        nuevaMemFija(cantpar);
    }//GEN-LAST:event_nropartActionPerformed
    
    private void nuevaMemFija(int cantPart){
        ArrayList<Integer> partFija = new ArrayList<>();
        for (int i=1; i<=cantPart; i++){
        Integer TamPart = Integer.parseInt((JOptionPane.showInputDialog(null, "Ingrese el tamaño de la partición nro " + i)));
	partFija.add(TamPart); 
        }
        System.out.println(partFija);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoPrograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarp;
    private javax.swing.JComboBox<String> algplanp;
    private javax.swing.JComboBox<String> combofija;
    private javax.swing.JComboBox<String> combovariable;
    private javax.swing.JTextField cpu1;
    private javax.swing.JTextField cpu2;
    private javax.swing.JTextField cpu3;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField entsal1;
    private javax.swing.JTextField entsal2;
    private javax.swing.JLabel fondomemo;
    private javax.swing.JLabel fondomemo1;
    private javax.swing.JLabel fondomemo2;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> nropart;
    private javax.swing.JTextField quantum;
    private javax.swing.JComboBox<String> rafagascpu;
    private javax.swing.JTextField tamanio;
    private javax.swing.JTextField tammemo;
    private javax.swing.JTextField tiempoarribo;
    private javax.swing.JComboBox<String> tipopart;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
