package modelo;
// Generated 17-sep-2019 17:13:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Memoria generated by hbm2java
 */
public class Memoria  implements java.io.Serializable {


     private Integer idmemoria;
     private String descripcion;
     private String tipoparticion;
     private String algasigmemo;
     private int tammemo;
     private int nroparticiones;
     private String algplanproc;
     private int quantum;
     private Set procesos = new HashSet(0);

    public Memoria() {
    }

    public Memoria(String descripcion, String tipoparticion, String algasigmemo, int tammemo, String algplanproc) {
        this.descripcion = descripcion;
        this.tipoparticion = tipoparticion;
        this.algasigmemo = algasigmemo;
        this.tammemo = tammemo;
        this.algplanproc = algplanproc;
    }

	
    public Memoria(String descripcion, String tipoparticion, String algasigmemo, int tammemo, int nroparticiones, String algplanproc, int quantum) {
        this.descripcion = descripcion;
        this.tipoparticion = tipoparticion;
        this.algasigmemo = algasigmemo;
        this.tammemo = tammemo;
        this.nroparticiones = nroparticiones;
        this.algplanproc = algplanproc;
        this.quantum = quantum;
    }
    public Memoria(String descripcion, String tipoparticion, String algasigmemo, int tammemo, int nroparticiones, String algplanproc, int quantum, Set procesos) {
       this.descripcion = descripcion;
       this.tipoparticion = tipoparticion;
       this.algasigmemo = algasigmemo;
       this.tammemo = tammemo;
       this.nroparticiones = nroparticiones;
       this.algplanproc = algplanproc;
       this.quantum = quantum;
       this.procesos = procesos;
    }
   
    public Integer getIdmemoria() {
        return this.idmemoria;
    }
    
    public void setIdmemoria(Integer idmemoria) {
        this.idmemoria = idmemoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipoparticion() {
        return this.tipoparticion;
    }
    
    public void setTipoparticion(String tipoparticion) {
        this.tipoparticion = tipoparticion;
    }
    public String getAlgasigmemo() {
        return this.algasigmemo;
    }
    
    public void setAlgasigmemo(String algasigmemo) {
        this.algasigmemo = algasigmemo;
    }
    public int getTammemo() {
        return this.tammemo;
    }
    
    public void setTammemo(int tammemo) {
        this.tammemo = tammemo;
    }
    public int getNroparticiones() {
        return this.nroparticiones;
    }
    
    public void setNroparticiones(int nroparticiones) {
        this.nroparticiones = nroparticiones;
    }
    public String getAlgplanproc() {
        return this.algplanproc;
    }
    
    public void setAlgplanproc(String algplanproc) {
        this.algplanproc = algplanproc;
    }
    public int getQuantum() {
        return this.quantum;
    }
    
    public void setQuantum(int quantum) {
        this.quantum = quantum;
    }
    public Set getProcesos() {
        return this.procesos;
    }
    
    public void setProcesos(Set procesos) {
        this.procesos = procesos;
    }




}


