package modelo;
// Generated 17-sep-2019 17:13:28 by Hibernate Tools 4.3.1



/**
 * Proceso generated by hbm2java
 */
public class Proceso  implements java.io.Serializable {


     public Integer idproceso;
     public Memoria memoria;
     public int tiempoarribo;
     public int tamanio;
     public int rafagascpu;
     public int cpu1;
     public Integer entsal1;
     public Integer cpu2;
     public Integer entsal2;
     public Integer cpu3;

    public Proceso(int tiempoarribo, int tamanio, int rafagascpu, int cpu1, Integer entsal1, Integer cpu2, Integer entsal2, Integer cpu3) {
        this.tiempoarribo = tiempoarribo;
        this.tamanio = tamanio;
        this.rafagascpu = rafagascpu;
        this.cpu1 = cpu1;
        this.entsal1 = entsal1;
        this.cpu2 = cpu2;
        this.entsal2 = entsal2;
        this.cpu3 = cpu3;
    }

    public Proceso(int tiempoarribo, int tamanio, int rafagascpu, int cpu1, Integer entsal1, Integer cpu2) {
        this.tiempoarribo = tiempoarribo;
        this.tamanio = tamanio;
        this.rafagascpu = rafagascpu;
        this.cpu1 = cpu1;
        this.entsal1 = entsal1;
        this.cpu2 = cpu2;
    }

    public Proceso(int tiempoarribo, int tamanio, int rafagascpu, int cpu1) {
        this.tiempoarribo = tiempoarribo;
        this.tamanio = tamanio;
        this.rafagascpu = rafagascpu;
        this.cpu1 = cpu1;
    }

    public Proceso() {
    }

	
    public Proceso(Memoria memoria, int tiempoarribo, int tamanio, int rafagascpu, int cpu1) {
        this.memoria = memoria;
        this.tiempoarribo = tiempoarribo;
        this.tamanio = tamanio;
        this.rafagascpu = rafagascpu;
        this.cpu1 = cpu1;
    }
    public Proceso(Memoria memoria, int tiempoarribo, int tamanio, int rafagascpu, int cpu1, Integer entsal1, Integer cpu2, Integer entsal2, Integer cpu3) {
       this.memoria = memoria;
       this.tiempoarribo = tiempoarribo;
       this.tamanio = tamanio;
       this.rafagascpu = rafagascpu;
       this.cpu1 = cpu1;
       this.entsal1 = entsal1;
       this.cpu2 = cpu2;
       this.entsal2 = entsal2;
       this.cpu3 = cpu3;
    }
   
    public Integer getIdproceso() {
        return this.idproceso;
    }
    
    public void setIdproceso(Integer idproceso) {
        this.idproceso = idproceso;
    }
    public Memoria getMemoria() {
        return this.memoria;
    }
    
    public void setMemoria(Memoria memoria) {
        this.memoria = memoria;
    }
    public int getTiempoarribo() {
        return this.tiempoarribo;
    }
    
    public void setTiempoarribo(int tiempoarribo) {
        this.tiempoarribo = tiempoarribo;
    }
    public int getTamanio() {
        return this.tamanio;
    }
    
    public void setTamanio(int tamanio) {
        this.tamanio = tamanio;
    }
    public int getRafagascpu() {
        return this.rafagascpu;
    }
    
    public void setRafagascpu(int rafagascpu) {
        this.rafagascpu = rafagascpu;
    }
    public int getCpu1() {
        return this.cpu1;
    }
    
    public void setCpu1(int cpu1) {
        this.cpu1 = cpu1;
    }
    public Integer getEntsal1() {
        return this.entsal1;
    }
    
    public void setEntsal1(Integer entsal1) {
        this.entsal1 = entsal1;
    }
    public Integer getCpu2() {
        return this.cpu2;
    }
    
    public void setCpu2(Integer cpu2) {
        this.cpu2 = cpu2;
    }
    public Integer getEntsal2() {
        return this.entsal2;
    }
    
    public void setEntsal2(Integer entsal2) {
        this.entsal2 = entsal2;
    }
    public Integer getCpu3() {
        return this.cpu3;
    }
    
    public void setCpu3(Integer cpu3) {
        this.cpu3 = cpu3;
    }




}


